name = "eduapps-th"
compatibility_date = "..."

[[d1_databases]]
binding = "DB"
database_name = "eduapps-db"
database_id = "f8b8a469-49e4-4f99-beb8-3b53d765345e"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "kruboard-img"
